### ISSUE TITLE
Brew tap reports an error with this tap

### ISSUE THREAD

**Issue by SanderSmee** [kordamp/homebrew-tap#1]
Given the environment below, `brew install kordamp/tap/gum` fails:

```shell
❯ brew install kordamp/tap/gum
==> Tapping kordamp/tap
Cloning into '/opt/homebrew/Library/Taps/kordamp/homebrew-tap'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 65 (delta 15), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (65/65), 13.96 KiB | 1.99 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/kordamp/homebrew-tap/Formula/pomchecker.rb
pomchecker: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the kordamp/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/kordamp/homebrew-tap/Formula/pomchecker.rb:9

Error: Cannot tap kordamp/tap: invalid syntax in tap!
```

`brew tap kordamp/tap` fails

~
❯ ruby -v
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

~
❯ uname -a
Darwin **** 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

~
❯ brew -v
Homebrew 3.4.2
Homebrew/homebrew-core (git revision 52453d3d930; last commit 2022-03-17)
Homebrew/homebrew-cask (git revision b667f5898b; last commit 2022-03-17)

~
❯ brew tap kordamp/tap
==> Tapping kordamp/tap
Cloning into '/opt/homebrew/Library/Taps/kordamp/homebrew-tap'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 65 (delta 15), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (65/65), 13.96 KiB | 433.00 KiB/s, done.
Resolving deltas: 100% (15/15), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/kordamp/homebrew-tap/Formula/pomchecker.rb
pomchecker: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the kordamp/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/kordamp/homebrew-tap/Formula/pomchecker.rb:9

Error: Cannot tap kordamp/tap: invalid syntax in tap!

**Comment by SanderSmee** [comment]
The error prevents me from installing [kordamp/tap/gum ](https://github.com/kordamp/gm) as described in its README installation section.

**Comment by aalmiray** [comment]
Ah. It looks like the pomchecker formula needs an update.
